### ISSUE TITLE
[epic] New Data Publisher 

### ISSUE THREAD

**Issue by risenW** [datopian/gift-publisher#1]
Make a working data publisher following this [mockup](https://www.figma.com/file/mHXBLk1O58jSDFeugJc5UN/GIFT-Publishing-Flow-w-Add-to-existing-flow?node-id=15%3A7)

## Acceptance

* [x] I have a working app ready to demo to the client.  **DONE: It's displayed at https://datopian.github.io/gift-publisher/**
* [x] Basic theme done similar to mockup **DONE: Redesign finalized in https://github.com/datopian/gift-publisher/pull/48**.
* [x] Upload steps implemented with screens **DONE: File upload progress has been implemented in https://github.com/datopian/gift-publisher/commit/a5b136dcdd8ef04e0ba3ee4004ed8ed2f9473ec0**.

## Tasks

* [x] Getting started
  * [x] Boot a git repo: gift-publisher
  * [x] Start a new DataPub based project https://github.com/datopian/datapub#getting-started
* [x] Stub the basic "resource creator" flow (we already have this) – See #2. **DONE: All set up.**
  * [x] file upload / link (note uploading won't be working for now because we don't have a backend)
  * [x] table schema editor
* [x] Set up static page/storybook. – See #4. **DONE: It's displayed at https://datopian.github.io/gift-publisher/**
* [x] Implement "steps" approach (with screens). – **DONE: This can be seen at https://datopian.github.io/gift-publisher/ See #3.**
* [x] Implement a static banner at the top showing the steps to be taken. – **DONE: Steps are shown at the top. See #6.**
* [x] Preview your data screen (table preview after upload screen) – **DONE: Reusing code from gift-portal to include the preview. See #9.**
* [x] Describe your data (Provide metadata)  **Done: See https://datopian.github.io/gift-publisher/**
  * [x] Do the work in background to serialize that to a model in fiscal data package in background – **DONE: See the [screen recording](https://github.com/datopian/gift-publisher/issues/12#issue-767504863) in #12 to see how this is being done**.
~~* Modify the schema editor step to reflect what we have here~~
~~* Validate your data - add this to the describe your data (happens in real time)~~

## Analysis

Proposing using a single page application, where each section/screen is hidden until the user clicks next. 
This is because we can easily maintain state as soon as a file is uploaded in the first screen. 

On file upload, we do the following:

* Start progress bar and wait for upload to complete (SCREEN 1)
  * Use progress component from datapub to show update
  * Perform upload (Needs more analysis) 
  * TODO: what about linking a file?
  * At end of this: we should have a Frictionless Dataset/Data Package object with a Data Resource with a sample and schema inferred.
    * Extract the sample onto the internal Data Resource object inside the Frictionless Data Package
    * Get schema from file using frictionless.js
* Once upload is complete, we can get a sample and show preview: (SCREEN 2) **Rufus: we could skip this for now and add later** 
  * No existing data preview component in datapub. We have to create a new component here. **Could we reuse Portal app code to display data? ~Rufus**
  * Display sample (~5) in a table using react-table-v7
* Show Table schema editor:  (SCREEN 3)
  * Use datapub TableSchema editor component
  * Tableschema component requires the file schema and a `sample` of data
  * Update Schema in background based on user edits
  * Adding new stuff to the table schema
  * TODO: ?? data validation
* After Table Schema, show describe metadata screen  (SCREEN 4)
  * No existing describe component in datapub, so we create one here
    * Could we generate off json schema? ~Rufus
  * ~~Generate data package (Background task) Remember to update the URL to the data!!!~~
  * ~~Validate data package (Background task) _Show fail or Pass_~~
* Final completion screen  (SCREEN 5)
    * Save button. Uploads datapackage.json

## NOTES on Re-using Datapub

Exported components cannot be styled. That means we have to use them as they are. Another option is to create our own components. 

## The State

```javascript=
{
  // other app state
  currentStep:
  // the dataset and its metadata
  dataset: { // Frictionless Dataset/Data Package object
    resources: [
      path: ...
      sha256: ...
      sample: ...
      schema: ...
    ]
  }
}
```

**Comment by risenW** [comment]
@sglavoie Can we close this issue now?

**Comment by sglavoie** [comment]
Yes, thank you @risenW :slightly_smiling_face:.

FIXED: All tasks were done. :tada: 

* App displayed at https://datopian.github.io/gift-publisher/ (functional and integrated at http://gift-portal-git-master.datopian1.vercel.app/)
* Basic theme done similar to mockup, redesign finalized in https://github.com/datopian/gift-publisher/pull/48
* Upload steps implemented with screens, then the progress bar was implemented in https://github.com/datopian/gift-publisher/commit/a5b136dcdd8ef04e0ba3ee4004ed8ed2f9473ec0
