### ISSUE TITLE
Serialize resource to fiscal data package in background

### ISSUE THREAD

**Issue by risenW** [datopian/gift-publisher#12]
Generate a datapackage.json from the uploaded resource

## Acceptance
* [x] A fiscal package is generated and saved in the state on file upload __Done__ See video below
* [x] Updates made by the user in both table schema and metadata screens are updated in the resource data package __Done__ See video below
Bonus: 
  * [x] I can download the generated datapackage.json __Done__ See video below

https://user-images.githubusercontent.com/29900845/103369237-e1ac9d00-4ac9-11eb-8cf0-74ac1f57184f.mp4

## Task
* [x] Create data package state variable and stub with properties from a resource file (0.1)
* [x] Create a mapper function that accepts data package  as an argument and returns a fiscal data package (0.6)
* [x] Update data package resource in state (0.2)
* [x] Update fiscal data package when the user makes changes to the schema (0.1)

## Analysis

* In the existing gift-publisher app: On file select (using titanic dataset as example) in the upload component, a resource file is generated and added to the state. A example of resource generated after uploading the titanic data is shown below:

```json=
{
"encoding":"utf-8",
"format":"csv",
"dialect":{"delimiter":",","quoteChar":"\""},
"schema":{
    "fields":[{"name":"PassengerId","type":"integer","format":"default"},
        {"name":"Survived","type":"integer","format":"default"},
        {"name":"Pclass","type":"integer","format":"default"},
        {"name":"Embarked","type":"string","format":"default"}],
        ...
    "missingValues":[""]
  },
  "hash":"7d118fef8b6ccf7f81111877bc388536f7b1e498a655e3d649d19aaa010e9f6f", // is this md5 or sha256. If sha256 this should be in a field called sha256 as hash is reserved to md5
  "sample":[[]],
"columns": [ // this should not be here IMO ...
    {"Header":"PassengerId","accessor":"PassengerId"},
    {"Header":"Survived","accessor":"Survived"},
    {"Header":"Pclass","accessor":"Pclass"},
    {"Header":"Name","accessor":"Name"},
    {"Header":"Sex","accessor":"Sex"}],
    ...
  "title":"titanic.csv"
}
```
* Using the resource above as our base, we can generate a data package state variable and stub with information from the state resource to have something like the following:
```json=
{
    "name": "",
    "title": "",
    "licenses": [],
    "resources": [
        {
            "name": "titanic.csv",
            "path": "",
            "title": "",
            "description": "",
            "format": "csv",
            "mediatype": "text/csv",
            "encoding": "utf-8",
            "bytes": 61194,
            "hash": "7d118fef8b6ccf7f81111877bc388536f7b1e498a655e3d649d19aaa010e9f6f",
            "schema": {
                "fields": [
                    {
                        "name": "PassengerId",
                        "type": "integer",
                        "format": "default"
                    },
                    {
                        "name": "Survived",
                        "type": "integer",
                        "format": "default"
                    },
                    ...
                ],
                "missingValues": [
                    ""
                ]
            }
        }
    ],
    "created": "",
    "keywords": [],
    "contributors": []
}
```
* Next, we can create a custom mapper just like the one in os-packager (reuse code/extend it). This function will accept the datapackage resource as argument, and automatically generate  rich-types. The resource is then returned as a fiscal data package. We can use the resources below to create this mapper function:
  * Existing [createFiscalPackage](https://github.com/openspending/os-packager/blob/master/app/services/package.js#L103) which we can copy and edit  
  * The [os-types](https://www.npmjs.com/package/os-types) npm package which maps fields in resources to fiscal column types. 
* Next, we update the data package state with the returned fiscal type

* Final step is to update datapackage state when user updates the rich type in the table schema editor.

**Comment by rufuspollock** [comment]
@risenW i think you could almost create the package when the app boots (later on we may load it with an existing package when doing editing ...). Then when file is linked or uploaded the *Resource* is created. Does that make sense.

**Comment by risenW** [comment]
> @risenW i think you could almost create the package when the app boots (later on we may load it with an existing package when doing editing ...). Then when file is linked or uploaded the _Resource_ is created. Does that make sense.

Yes it does, its similar to what we have currently in datapub-nhs.
