### ISSUE TITLE
ColumnType editor for Fiscal Data packages

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-publisher#17]
We want to extend/adapt the existing table schema editor in DataPub to support adding a `columnType` attribute using a rich set of types. Default types would be os-types but this should be something that can be passed into the app so that we can customize the set of types.

## Background

Read about Fiscal Data Package: https://specs.frictionlessdata.io/fiscal-data-package

Suppose I have a csv like this

```
Amount, Year, Classification
200, 2020, Guns
400, 2020, Butter
```

In Tabular Data package we would have a schema like:

```json=
fields: [
  {
   name: "Amount",
   type: "integer"
  },
  {
   name: "Year",
   type: "year"
  },
  {
   name: "Classification",
   type: "string"
  }
]
```

Need: Suppose I want to describe the fields (columns) in my data in a rich semantic way, not just that they are numbers or strings but that e.g. the Amount field is about the "amount of money spent".

We do this by adding a `columnType` attribute on the field e.g. `Amount` field would become:

```json=
  {
    "name": "Amount",
    "type": "number",
    "columnType": "value"
  },
  {
    "name": "Year",
    "type": "year",
    "columnType": ...
  },
  {
    "name": "Classification",
    "type": "string",
    "columnType": "administrative:classification:generic:label"
  }
```

## Acceptance

* [x] When i am in the data describe section (aka table schema editor) I want to be able to provide an additional attribute "Rich Type" for each column so that is stored as the columnType in the resource field in the data package __Done__ Can test in the [live app](https://datopian.github.io/gift-publisher/) or see GIF below.
  * In terms of UI: basic drop down is good to start. Next step would be filter as i type e.g. if i type `act` i am only shown column types that match `act`
  * The result should be that the resource schema has columnType set ...
* [x] I can configure the set of rich types that are used by the application __Done__ A config JSON files can be supplied at build time

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29900845/103221399-d0755c00-4922-11eb-8e71-95746f119053.gif)

## Tasks

* [x] Get column types
* [x] Add column type editor to schema editor

### Get column types

* [x] Get a test list of column types
* [x] Editor app should take column types as an argument when booting up

### Add column type editor to schema editor

* [x] Add columnType to all fields (if not already present) prior to booting schema editor
* [x] Copy and paste schema editor
* [x] Add new if statement https://github.com/datopian/datapub/blob/master/src/components/TableSchema/index.jsx#L42 `if key == columnType` and have select/dropdown field with auto complete
  * [x] BONUS: Show a description e.g. https://github.com/openspending/os-types/blob/master/src/os-type-descriptions.json next to the item (or below) in the dropdown list
    * ie. in select "`activity:abc` - label for this one"
    * NB: this is bonus. Let's think about this later.

Reference: Figma mockup (to be edited) https://www.figma.com/file/TX849YGwnoq5l8387x5DTj/GIFT-Publishing-Flow

### Existing Table Schema Editor

* Table schema code: https://github.com/datopian/datapub/blob/master/src/components/TableSchema/index.jsx
* gift publisher code: 
Table previewer >> https://github.com/datopian/gift-publisher/blob/main/src/components/tablePreview/index.js

### Old os-packager

* Next, we can create a custom function just like the one in os-packager (reuse code/extend it). This function will accept the datapackage resource as argument, and automatically infer rich-types. The resource is then returned as a fiscal data package. We can use the resources below to create this mapper function:
  * Existing [createFiscalPackage](https://github.com/openspending/os-packager/blob/master/app/services/package.js#L103) which we can copy and edit  
  * The [os-types](https://www.npmjs.com/package/os-types) npm package which maps fields in resources to fiscal column types. 
* Next, we update the data package state with the returned fiscal type, to have something like:
```json=
{
    "name": "",
    "title": "",
    "licenses": [],
    "resources": [
        {
            "name": "titanic.csv",
            "path": "",
            "title": "",
            "description": "",
            "format": "csv",
            "mediatype": "text/csv",
            "encoding": "utf-8",
            "bytes": 61194,
            "hash": "7d118fef8b6ccf7f81111877bc388536f7b1e498a655e3d649d19aaa010e9f6f",
            "schema": {
                "fields": [
                    {
                        "name": "PassengerId",
                        "type": "integer",
                        "format": "default",
                        "columnType": "administrative-classification:generic:code"
                    },
                    {
                        "name": "Survived",
                        "type": "integer",
                        "format": "default",
                        "columnType": "value"
                    },
                    ...
                ],
                "missingValues": [
                    ""
                ]
            }
        }
    ],
    "created": "",
    "keywords": [],
    "contributors": []
}
```
* Next, we extend the table schema component by adding a dropdown/select section which maps each field/column in the schema to the rich type. Each dropdown will contain the full list of fiscal types as specified [here](https://github.com/openspending/os-types/blob/master/src/os-types.json), but by default will display the inferred fiscal type from our mapper function. 

* Final step is to update datapackage state when user updates the rich type in the table schema editor. 

#### OLD

* List of types: https://github.com/openspending/os-types and specifically:
https://github.com/openspending/os-types/blob/master/src/os-types.json
* Key describe data step:
  * Template: https://github.com/openspending/os-packager/blob/master/app/views/partials/steps/describe-data.html
  * Core code: https://github.com/openspending/os-packager/blob/master/app/front/scripts/services/describe-data.js
  * Controller: https://github.com/openspending/os-packager/blob/master/app/front/scripts/controllers/describe-data.js

**Comment by sglavoie** [comment]
**Update**:

* Mockups done, see screenshots in https://github.com/datopian/client-gift/issues/11 (not pasting here since there are a couple of them).
* A `sample` property was added to all the GIFT repos at https://github.com/gift-data/. Example: https://github.com/gift-data/paraguay-2017/blob/master/datapackage.json#L229
  * The first array in this nested array structure contains the name of the columns (header row) while subsequent arrays each correspond to a row of data taken from the top of the CSV files.
  * More details and scripts used to do that in https://github.com/datopian/client-gift/issues/9.
  * Only 50 rows were added to the `sample` property because some datasets have quite a few columns generating a large output. The number of rows to add to `sample` is configurable as expected.

/cc @rufuspollock @risenW
