### ISSUE TITLE
[Provide Metadata screen] Redesign the component to make it easier to use and to show only relevant information

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#22]
When I reach the "Provide Metadata" page when following the Publisher flow, I want to see the information in a way that makes it easy to read and to understand what has to be done so I can confidently input the information I think makes the most sense and go to the next step generating a properly described dataset without facing errors later on (e.g. encoding error when updating a dataset because I didn't know what to do).

## Acceptance

* [x] The "Provide Metadata" page of [gift-publisher](https://github.com/datopian/gift-publisher) has been redesigned to fulfill our needs (see sub-criteria). **Done** See short video below
  * [x] Make the fields easier to read, with an accompanying description for each one (e.g. "Encoding" field should say UTF-8 is preferable like it's the case in the mock-ups).
  * [x] The field "Access Restriction" has been removed (controlled via GitHub interface). **DONE: not displayed anymore.** @risenW 
  * [x] The "Format" dropdown menu only shows "CSV" **DONE: CSV is the only option we can choose.** @risenW 
  * [x] When publishing a dataset (create or edit flow), the user can fill out all the required metadata:
    * [x] Dataset description
    * [x] Country
    * [x] Continent
    * [x] City
    * [x] Tags
    * [x] Region
    * [x] Author's website
    * [x] Author's email address
    * [x] Fiscal period (start and end dates)

* [x] [side quest] The [first step of the publisher flow](https://datopian.github.io/gift-publisher/) shows the text `Supported format: CSV` instead of `Supported formats: csv, xlsx, xls`.

https://user-images.githubusercontent.com/29900845/107536116-b71e2b80-6bc1-11eb-8720-78628a4995cf.mov

## Tasks

* [x] Update the "Provide Metadata" page of the [Figma mock-ups](https://www.figma.com/file/TX849YGwnoq5l8387x5DTj/GIFT-Publishing-Flow?node-id=0%3A1) to show what we need. **@sglavoie** {<0.5} – **DONE: See mock-ups and [screenshots below](https://github.com/datopian/gift-publisher/issues/22#issuecomment-776113573).**
* [x] Update the necessary application component according to the [Figma mock-ups](https://www.figma.com/file/TX849YGwnoq5l8387x5DTj/GIFT-Publishing-Flow?node-id=0%3A1) (See [screenshots below](https://github.com/datopian/gift-publisher/issues/22#issuecomment-756896544)).

**Comment by sglavoie** [comment]
**[Figma mock-ups](https://www.figma.com/file/TX849YGwnoq5l8387x5DTj/GIFT-Publishing-Flow?node-id=0%3A1) updated**:

![New flow - Provide metadata](https://user-images.githubusercontent.com/32682903/104046014-0e854200-51a5-11eb-99e9-82d6ab2d2044.png)
![New flow - Provide metadata-1](https://user-images.githubusercontent.com/32682903/104046016-0e854200-51a5-11eb-860e-cf7f5d4d2d32.png)
![New flow - Provide metadata-2](https://user-images.githubusercontent.com/32682903/104046017-0f1dd880-51a5-11eb-9940-fda99f97b794.png)

**Comment by sglavoie** [comment]
@risenW @steveoni I have now updated the mock-ups, keeping it closer to what it currently looks like in the Publisher. I'm not sure which one of you would take this one on, so I'm letting both of you know. Have a great weekend in the meantime! :wave: :wink:

**Comment by sglavoie** [comment]
@risenW This issue could also be on your list once you get to it :wink:. We can fix the layout for now and make minor changes to the CSS later once we're done with almost everything else.

**Comment by sglavoie** [comment]
@risenW I have updated this issue to include missing fields in the "Provide metadata" screen. However, that means the mock-ups also need to be updated, so I'll let you know once they're ready to go. :wink:

**Comment by sglavoie** [comment]
@risenW Mock-ups done! Those are all the fields we need to support in the "Provide metadata" screen (the image is quite big if you want to open it in a new tab):

<img width="1440" alt="Provide_metadata_screen" src="https://user-images.githubusercontent.com/32682903/107402377-7f33bd00-6ac9-11eb-9e81-1b9d6d865c17.png">

This issue will also be closely related to https://github.com/datopian/gift-portal/issues/110 to contemplate the situation in which we don't have data being inputted for a specific field.


The dropdown menu for `Continent` and `Country` could work just like the `Rich Type` field in the schema editor which gives the ability to filter the results by typing. The fiscal years could use a calendar widget or could be used by filling up placeholder text accepting only digits, where the placeholder would show `YYYY - MM - DD` and disappear as we type (or similar).

![2021-02-09_11-32](https://user-images.githubusercontent.com/32682903/107403378-a8a11880-6aca-11eb-8a9c-a58c9ed5483c.png)

**Comment by risenW** [comment]
@sglavoie Is there a specified list of tags that a user must fill from, or can they add any tag of their choice?
