### ISSUE TITLE
Cleanup publisher UI 

### ISSUE THREAD

**Issue by risenW** [datopian/gift-publisher#23]
Perform some basic cleanup of the gift-publisher UI

### Acceptance
* [x] When I'm in the metadata edit screen, I do not want to see the `access restriction` field **Done** See screenshots below
* [x] When I'm in the metadata edit screen, I want the format to be CSV only. **Done** See screenshots below
* [x] When I'm in the metadata edit screen, I want the description field to be a multiline textbox **Done** See screenshots below
* [x] When I'm in the metadata edit screen, I want the button to say `save` instead of `save and publish` **Done** See screenshots below
* [x] When I'm in the describe your data screen, I should not be able to go to the next page until all required fields have been filled. All required fields are ( Rich Type ). **Done** See screenshots below

<img width="1237" alt="Screen Shot 2021-01-12 at 2 10 50 PM" src="https://user-images.githubusercontent.com/29900845/104318970-778bf300-54e0-11eb-9550-41d443ef23ef.png">

<img width="932" alt="Screen Shot 2021-01-12 at 2 12 35 PM" src="https://user-images.githubusercontent.com/29900845/104318983-7e1a6a80-54e0-11eb-826e-0e4f420d15db.png">

<img width="911" alt="Screen Shot 2021-01-12 at 2 13 12 PM" src="https://user-images.githubusercontent.com/29900845/104319003-84104b80-54e0-11eb-8b48-6f6061eb09b1.png">

### Task
* [x] Remove the `access restriction` field
* [x] Remove all other formats except CSV from the file format select option.
* [x] Change the file description input field to a multiline textbox
* [x] Change  `save and publish` button to say `save`
* [x] Check if required fields (Rich Type) have been filled before enabling the next button
