### ISSUE TITLE
Enable CORS support on the Giftless server at Heroku

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#25]
Parent issue: #21 

When I send network requests to the Giftless server at Heroku (https://giftless-gift.herokuapp.com), I want to get a reply back from the server without facing CORS issues so I can test remotely everything I need with gift-publisher.

## Acceptance

* [x] CORS support has been added to the Giftless server hosted on Heroku and has been confirmed to be working. **DONE: The Python package `wsgi_cors_middleware` was added, a `MIDDLEWARE` section was added to the config file and the server was redeployed and tested by @steveoni. See https://github.com/datopian/giftless-server-heroku-dev/commit/c1f6b5a5a13ffef09e6a8bd2913d2b33b1015d1a and https://github.com/datopian/giftless-server-heroku-dev/commit/24efdc2fc7bc5e13ff4696b8efc7e4934811ff68 for details.**

## Tasks

* [x] Move private repo to Datopian organization (containing Heroku configuration details used for testing purposes). **DONE: private repo here https://github.com/datopian/giftless-server-heroku-dev**
  * [x] Update Git remote URL in local repo.
* [x] Install the Python package `wsgi_cors_middleware` with the Giftless server on Heroku (update `requirements.txt`). **DONE: See https://github.com/datopian/giftless-server-heroku-dev/commit/c1f6b5a5a13ffef09e6a8bd2913d2b33b1015d1a**
* [x] Add a `MIDDLEWARE` section in the Giftless configuration file to enable CORS support. **DONE: See https://github.com/datopian/giftless-server-heroku-dev/commit/24efdc2fc7bc5e13ff4696b8efc7e4934811ff68**
* [x] Test locally with the command `heroku local`. **DONE: Looks good locally, no errors.**
* [x] Redeploy to Heroku with the new configuration. **DONE: Release v18 on Heroku.**
* [x] Confirm with @steveoni that it does indeed work. **DONE: Steven said it worked.**

## Analysis

* CORS support need to be added with a Python package as well as by modifying the Giftless server configuration file. See https://github.com/datopian/giftless#adding-cors-support for details.
* `MIDDLEWARE` section should contain the following (skipping the keyword argument `origin` will allow requests from everywhere by default [ref: [moritzmhmk/wsgi-cors-middleware/blob/master/wsgi_cors_middleware.py](https://github.com/moritzmhmk/wsgi-cors-middleware/blob/master/wsgi_cors_middleware.py)]):

```
MIDDLEWARE:
  - class: wsgi_cors_middleware:CorsMiddleware
    kwargs:
      headers: ['Content-type', 'Accept', 'Authorization']
      methods: ['GET', 'POST', 'PUT']
```

**Comment by sglavoie** [comment]
FIXED: The Python package `wsgi_cors_middleware` was added, a `MIDDLEWARE` section was added to the config file and the server was redeployed and tested by @steveoni. See https://github.com/datopian/giftless-server-heroku-dev/commit/c1f6b5a5a13ffef09e6a8bd2913d2b33b1015d1a and https://github.com/datopian/giftless-server-heroku-dev/commit/24efdc2fc7bc5e13ff4696b8efc7e4934811ff68 for details.
