### ISSUE TITLE
Automatic Build

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-publisher#27]
Anytime there is a new update to publisher app, I want to build the component without including css and automatically update the `lib/components` without affecting the default components at `src/components`

## Acceptance

* [x] There should be a separate directory for the build components not containing css in `src/lib/components` **DONE** https://github.com/datopian/gift-publisher/tree/main/src/lib
* [x] The build should be store in `dist/` for easy integration into `gift-portal` **DONE** - https://github.com/datopian/gift-publisher/tree/main/dist

## Task

* [x] create a script to transfer codes in `src/` to `src/lib` **DONE** - https://github.com/datopian/gift-publisher/blob/main/src/copy.js
* [x] remove every css import in the updated code **DONE**
* [x] add command to build **DONE** - https://github.com/datopian/gift-publisher/blob/main/package.json

**Comment by risenW** [comment]
@steveoni I thought you were done with this issue, No?

**Comment by steveoni** [comment]
yeah
