### ISSUE TITLE
Implement "steps" approach (with screens)

### ISSUE THREAD

**Issue by risenW** [datopian/gift-publisher#3]
## Acceptance
* [x]  I have 3 screens (Upload, Tableschema, and Metadata) and corresponding next and a back button which I9 can toggle to display the information on the screen. __Done__ https://datopian.github.io/gift-publisher/

## Analysis
Proposing using a single page application, where each section/screen is hidden until the user clicks next. 
This is because we can easily maintain the state as soon as a file is uploaded on the first screen. 

## Task
* [x] Stub Gift-publisher with components and code from [datapub-nhs](https://github.com/datopian/datapub-nhs), since they're similar
* [x] Add next and back state button
* [x]  Add minimal styling

**Comment by sglavoie** [comment]
@risenW I started updating the mock-ups for the publishing flow. I wasn't feeling too well, so didn't manage to finish. :disappointed: 

However you choose to implement the next steps starting on Monday, I can always adapt the rest of the mock-ups so they'll look closer to what you are doing. For now, I'm working in this file to keep changes separate: https://www.figma.com/file/ynhgabBt9nBpfZ151LdbfH/GIFT---Publishing-Flow---Simplified-(no-back%2Fnext-%2B-steps-shown)?node-id=15%3A7

The idea remains that it will look like the components we have in Datapub, something like so:

![image](https://user-images.githubusercontent.com/32682903/101954413-abae8400-3bc1-11eb-8671-26b1bf83227b.png)

![image](https://user-images.githubusercontent.com/32682903/101954448-bf59ea80-3bc1-11eb-9011-0e9356f49544.png)

![image](https://user-images.githubusercontent.com/32682903/101954484-cf71ca00-3bc1-11eb-8767-42d61b24571d.png)

![image](https://user-images.githubusercontent.com/32682903/101954516-dac4f580-3bc1-11eb-8764-28a327b5e4aa.png)

In any case, we can review in our daily stand-up whether you're being blocked and what you will have done by that point, so that's not a big issue.

Have a great weekend for now. :slightly_smiling_face: :wave:
