### ISSUE TITLE
Update fiscal data package

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-publisher#34]
When we have the publisher booted in edit mode, we want to be able to make updates to the fiscal data.

## Aceptance
* [ ] update the fiscal data package in the `Metadata` edit flow

## Task

* [ ] edit `ResourceEditor` to accept datapackage has props from `gift-portal`
* [ ] update metadata fields in datapackage.json on edit Metadata workflow.

**Comment by risenW** [comment]
@steveoni Is this not what you worked on here ==> #35

**Comment by steveoni** [comment]
no. this issue was discarded then and replace with this https://github.com/datopian/gift-portal/issues/79

**Comment by rufuspollock** [comment]
DUPLICATE. See #79
