### ISSUE TITLE
Rework Screen 1: provide data screen (file upload)

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#36]
* Part of Epic https://github.com/datopian/gift-portal/issues/91

## Acceptance

* [x] Displays all the files in this dataset in a simple way (maybe a table) **Done** See video Below
* [x] Can remove files **Done** See video Below
* [x] Can add files (One at a time for now) **Done** See video Below
  * [x] when we add a file that isn't the first we check if file has same columns as first file in list **Done** See video Below
* [x] Cannot move to next screen without having at least one file **Done** See video Below

https://user-images.githubusercontent.com/29900845/107044312-6757f280-67c4-11eb-93d1-bc2b9a7dffcd.mov

## Task

* [x] ⭐⭐ Add a file list UI component that uses `dataset.resources` and updates as it changes
  * [x] Have remove buttons that remove this resource from the resources array
* [x] Allow to add a file
  * ❓️ TODO: do we allow you to initiate multiple file uploads at once ... (No for now)
  * [x] After upload completes show option to "add another file"
* [x] ⭐ After upload completes and resource schema is inferred IF this is NOT the first resource => run a check that this has the same fields as first resource
  * [x] ⭐ Display relevant error messages
* [x] ⭐⭐⭐ Add a "next" button
  * [x] ⭐ Only allow next button to be clicked if no errors re unmatched fields
