### ISSUE TITLE
[checklist][dataset page] All fields in the schema editor should contain data and be accessible by an authenticated user only

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#42]
## Acceptance

* [x] All the fields in the schema editor must be filled before the user can go to the next step (i.e. `Rich Type`, `Title` and `Description` must contain data in all their fields). **DONE** 
* [x] An unauthenticated user should be redirected to the main page (or a 404 error should be displayed) when trying to access any dataset without being logged in (e.g. going to https://gift-portal-git-master.datopian1.vercel.app/admin/publisher/presupuesto-mexico-2008-2019 when logged out should redirect to the main page or show a 404 error instead of showing the publisher application). **DONE**
* [x] Accessing an inexistant dataset (e.g. https://gift-portal-git-master.datopian1.vercel.app/admin/publisher/pasdfasd) either redirects to the main page of the portal or shows a 404 error. **DONE**

## Tasks

* [x] check log in user in `admin/publisher/[id]` and always show 404 if a user is not logged in **DONE** - https://github.com/datopian/gift-portal/blob/fix-publisher/pages/admin/publisher/%5Bid%5D.js
* [x] Put data fetching from `MetaStore` in a try block to prevent 502 error **DONE** - https://github.com/datopian/gift-portal/blob/fix-publisher/pages/admin/publisher/%5Bid%5D.js
* [x] Update Publisher app and check if the right fields are filled before moving to the next step **DONE** - https://github.com/datopian/gift-publisher/blob/schema-field/src/components/TableSchema/index.jsx

## Analysis

* All the `Rich Type` fields should be filled before the user can go to the next step.
  * Currently, one can fill out other fields in each column and that would allow the user to go to the next step regardless of which field was filled in (so `Rich Type` does not necessarily have a value selected).
* Accessing an inexistant dataset (e.g. https://gift-portal-git-master.datopian1.vercel.app/admin/publisher/pasdfasd) either redirects to the main page of the portal or shows a 404 error.
  * Currently, this situation is not handled and leads to a 502 error being displayed.

**Comment by steveoni** [comment]
@sglavoie once this pull request https://github.com/datopian/gift-publisher/pull/52 is accepted and I will update the gift-publisher in gift-portal and then create a pull request for this issue.

**Comment by sglavoie** [comment]
Awesome! Thank you for leaving your comment here. :slightly_smiling_face:
