### ISSUE TITLE
Giftless server should be configured to require a token to push data to it and the publisher generates such tokens to communicate with the server

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#45]
## Acceptance

- [ ] Upload to the cloud storage via Giftless fails when no valid token is provided.
- [ ] The publisher generates valid tokens to communicate with the Giftless server to upload resources to the cloud.

## Tasks

- [ ] Update token config - GIFT Portal, see https://github.com/datopian/gift-portal/issues/138
- [ ] Update giftless routes workflow

## Analysis

* At this time, there is no token check happening on the Giftless server on Heroku.
