### ISSUE TITLE
Add data sample to metadata 

### ISSUE THREAD

**Issue by risenW** [datopian/gift-publisher#46]
The sample field in a data package is used when displaying samples in Gift-portal. This should be auto-generated from the first resource and added to the top-level data package.

## Acceptance
* [x] I have a `sample` property in the data package with at least 10 rows from the first resource-if available.  **Done** https://github.com/datopian/gift-publisher/pull/50
* [x] the sample property is empty if there's no resource

## Task
* [x] Check if the dataset passed to the publisher has a sample property. If no sample:
  * [x] Set sample property to the empty array if there's no resource
* [x] On upload of the first resource, add a `sample` property in the dataset state variable with at least 10 rows.
