### ISSUE TITLE
Progress screen

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-publisher#6]
When I visit the publishing app, I want to see all the steps I will be taking when adding a new dataset so I can follow the on-screen instructions unambiguously with a clear expectation of what the next step to come will be.

### Acceptance

* [ ] The Progress screen must be the same as the mockup design (https://www.figma.com/file/ynhgabBt9nBpfZ151LdbfH/GIFT---Publishing-Flow---Simplified-(no-back%2Fnext-%2B-steps-shown)?node-id=15%3A7) and in relation to #3. See the screenshot in the **Analysis** section below.

## Tasks

* [x] Export an SVG of the whole "component" so it can be placed at the top of the page to scale well on all screen sizes. – @sglavoie — **DONE**: We have the SVG and suggested code to include it in the app (see [this comment below](https://github.com/datopian/gift-publisher/issues/6#issuecomment-744597060)).
* [x] Add this static element (image) showing the steps at the top so it renders correctly when adding a dataset while following the flow (no dynamic change expected for now). – @steveoni --- **DONE**. Non-dynamic progress-screen now added to the publisher in #13 

## Analysis

Show users the progress steps of publishing their data, base on the mockup design (https://www.figma.com/file/ynhgabBt9nBpfZ151LdbfH/GIFT---Publishing-Flow---Simplified-(no-back%2Fnext-%2B-steps-shown)?node-id=15%3A7).

The information to be shown will look as follows:

![image](https://user-images.githubusercontent.com/32682903/102112621-92921700-3dfd-11eb-9ae1-a008f3c50b14.png)

**Comment by sglavoie** [comment]
@steveoni I've exported the SVG image:

[steps.svg.zip](https://github.com/datopian/gift-publisher/files/5690546/steps.svg.zip)

I think if we just embed this within an `img` tag it should scale well. I tested with the following code and it seems to render nicely:

```
    <div style="text-align: center;">
      <img src="/path/to/file/steps.svg" style="width: 80%; max-width: 1440px;" />
    </div>
```

We may want to adjust the `width` and `max-width` properties, but I think that kind of styling will work well. Otherwise, if that's useful to you, I've seen this article which covers different options for scaling SVGs: https://css-tricks.com/scale-svg/#how-to-scale-svg-to-fit-the-available-width-and-adjust-the-height-to-match
