### ISSUE TITLE
Cannot upload a resource and commit changes made to GitHub from a newly created dataset

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#64]
When I upload a dataset, I expect it to have been uploaded once successfully so I can fill the necessary information (describe the fields + metadata) and be able to click on `Save` at the end of the flow, saving the metadata to GitHub.

## Acceptance

* [ ] I can save metadata from any uploaded resource (e.g. this one https://storage.googleapis.com/gift-datasets/gift-data/MDEwOlJlcG9zaXRvcnkzNDM4NjcwOTc%3D/8f2f06c279461768c64f11250b2615fbc8059bd743f58a2f40b4541e53244a65) successfully.

## Tasks

* [x] Validate user cookie method
* [x] Remove cookie when user log out
* [x] Update pages to validate `session` and `cookie

## Analysis

It looks like a permission issue. I was able to push a large file here https://github.com/gift-data/costa-rica-presupuesto-ingresos-2020/blob/main/data/simple_heavy4.csv for an existing repo (created by @sglavoie back in September 2020) but nothing at all to a new repo like this one (created by @sglavoie on March 2, 2021) https://github.com/gift-data/paraguay-2017

I thought maybe it had to do with the fact that I deleted the repo and created a new one with the same name, but the same happens with this other one I created later: https://github.com/gift-data/paraguay-2017-2

Simple files (4 columns) of different sizes could be used from this dataset (see in Google Cloud): gift-datasets/gift-data/MDEwOlJlcG9zaXRvcnkzNDM4NjcwOTc=

----

**Note:** Once the metadata is updated and the button `Save` is clicked, the message `Uploaded successfully.` is shown when the information was successfully saved. However, no resource should be uploaded at this point: only the metadata should be updated, so the message is misleading.

When starting from the beginning of the flow by clicking on `Create a fiscal data schema`, all steps can succeed until one clicks on the `Save` button, at which point the message `An Error occurred when uploading the dataset!` appears and nothing gets saved to GitHub. This is true when trying to upload a file for this dataset https://github.com/gift-data/paraguay-2017, the file being online here https://storage.googleapis.com/gift-datasets/gift-data/MDEwOlJlcG9zaXRvcnkzNDM4NjcwOTc%3D/8f2f06c279461768c64f11250b2615fbc8059bd743f58a2f40b4541e53244a65 (as can be seen, the dataset ID is `MDEwOlJlcG9zaXRvcnkzNDM4NjcwOTc=`).

The above upload, once the data is described and the metadata filled, shows the following error in the JavaScript console:

```
853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1 POST https://gift-portal-git-master-datopian1.vercel.app/api/dataset/paraguay-2017 400
(anonymous) @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
e.exports @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
UnBK.e.exports @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
Promise.then (async)
CgaS.c.request @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
(anonymous) @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
(anonymous) @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
s @ 74a5bdab7c46be5812a5ed28b29adc92ff928d99.5c3b22bc5e17b1375a1c.js:1
(anonymous) @ 74a5bdab7c46be5812a5ed28b29adc92ff928d99.5c3b22bc5e17b1375a1c.js:1
(anonymous) @ 74a5bdab7c46be5812a5ed28b29adc92ff928d99.5c3b22bc5e17b1375a1c.js:1
m @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
s @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
(anonymous) @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
(anonymous) @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
onSubmit @ 853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1
We @ framework.0c239260661ae1d12aa2.js:1
Ye @ framework.0c239260661ae1d12aa2.js:1
(anonymous) @ framework.0c239260661ae1d12aa2.js:1
xr @ framework.0c239260661ae1d12aa2.js:1
Cr @ framework.0c239260661ae1d12aa2.js:1
(anonymous) @ framework.0c239260661ae1d12aa2.js:1
De @ framework.0c239260661ae1d12aa2.js:1
(anonymous) @ framework.0c239260661ae1d12aa2.js:1
Or @ framework.0c239260661ae1d12aa2.js:1
Zt @ framework.0c239260661ae1d12aa2.js:1
Jt @ framework.0c239260661ae1d12aa2.js:1
t.unstable_runWithPriority @ framework.0c239260661ae1d12aa2.js:1
Wl @ framework.0c239260661ae1d12aa2.js:1
Me @ framework.0c239260661ae1d12aa2.js:1
Xt @ framework.0c239260661ae1d12aa2.js:1
853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1 Error: Request failed with status code 400
    at LYNF.e.exports (853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1)
    at Rn+g.e.exports (853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1)
    at XMLHttpRequest.h.onreadystatechange (853903f82485797d365e8e24b62de66875bdb751.51264a085ddf6bb56323.js:1)
```

The file size doesn't matter.

**Comment by sglavoie** [comment]
Hypothesis left by @risenW:

> Probably expired JWT session, because the JWT decrypt function is not decrypting the logged-in user. @cotts  Here's the line where the error is coming from: https://github.com/datopian/gift-portal/blob/e1239b98a506cd2e5957be6ac42d692874eea3e7/pages/api/dataset/%5Bid%5D.js#L16

I've tested this (once) by logging out and logging back in again and couldn't update metadata for a newly created dataset like this one :man_shrugging: : https://github.com/gift-data/paraguay-2017

**Comment by cotts** [comment]
The User Information that came from cookie is fixed on [this PR](https://github.com/datopian/gift-portal/pull/156).
There is another issue related to the `metastore-lib` when trying to save metadata

``` 
TypeError: Cannot use 'in' operator to search for 'revision' in undefined
    at /home/cotts/workspace/datopian/GIFT/gift-portal/node_modules/metastore-lib-js/dist/backend/github.js:164:43
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by sglavoie** [comment]
@cotts The same error keeps happening when saving metadata. Is this fixed as part of https://github.com/datopian/gift-portal/pull/157?
