### ISSUE TITLE
`datapackage.json` should contain only one `schema` property and keep track of `sample` appropriately

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#66]
* When I add my first resource to a newly created dataset, I want to show a `sample` property containing **maximum 30 rows** inside the resource with **no `sample` property at the top-level** so I can keep the file short and sweet.\*
* When I add my first resource to a newly created dataset, I want to show a `schema` property inside the resource but **no `schema` at the top-level** of `datapackage.json`.\*

\* This is so because the `schema` and `sample` will be retrieved only from the first available resource and there's no need to duplicate them at the top-level.

## Acceptance

* [x] There is **no `schema` property at the top-level** of the `datapackage.json` for a given dataset and all the resources in the dataset contain a **non-empty `schema` property**. **Done** See https://github.com/datopian/gift-publisher/pull/65
* [x] There is **no `sample` property at the top-level** of the `datapackage.json` for a given dataset and there's a **`sample` property inside each resource** containing a **maximum of 30 rows**. **Done** See https://github.com/datopian/gift-publisher/pull/65
* [x] When a resource is deleted, the `sample` property to show a preview of the dataset is **retrieved from the first resource available**. Therefore, there is always some content for the `sample` property as long as we have at least one resource in a dataset.
* [x] When a resource is deleted, the `schema` property to describe the dataset when uploading a new resource is **retrieved from the first resource available**. Therefore, there is always some content for the `schema` property as long as we have at least one resource in a dataset – which means we do not enforce a specific schema when all resources are deleted from a dataset.

Below is an example output from this [fix]( https://github.com/datopian/gift-publisher/pull/65)

```json
{
    "encoding": "utf_8",
    "format": "csv",
    "resources": [
        {
            "bytes": 2839,
            "hash": "af6609cdf1dad0b699bd3414c13e999b2c2f651972f0938254a835985d584306",
            "format": "csv",
            "schema": {
                "fields": [
                    {
                        "title": "v bvcbc",
                        "name": "PassengerId",
                        "slug": "PassengerId",
                        "type": "string",
                        "format": "default",
                        "columnType": "activity:generic:contract:label",
                        "conceptType": "activity",
                        "options": []
                    },
                    {
                        "title": "cx cx",
                        "name": "Survived",
                        "slug": "Survived",
                        "type": "string",
                        "format": "default",
                        "columnType": "activity:generic:contract:code",
                        "conceptType": "activity",
                        "options": []
                    }
                ],
                "missingValues": [
                    ""
                ]
            },
            "encoding": "utf-8",
            "mediatype": "text/csv",
            "name": "submission.csv",
            "dialect": {
                "delimiter": ",",
                "quoteChar": "\""
            },
            "path": "data/submission.csv",
            "sample": [
                [
                    "PassengerId",
                    "Survived"
                ],
                [
                    "892",
                    "0"
                ],
                [
                    "893",
                    "1"
                ],
                [
                    "894",
                    "0"
                ],
                [
                    "895",
                    "0"
                ],
                [
                    "896",
                    "1"
                ],
                [
                    "897",
                    "0"
                ],
                [
                    "898",
                    "1"
                ],
                [
                    "899",
                    "0"
                ],
                [
                    "900",
                    "1"
                ],
                [
                    "901",
                    "0"
                ],
                [
                    "902",
                    "0"
                ],
                [
                    "903",
                    "0"
                ],
                [
                    "904",
                    "1"
                ],
                [
                    "905",
                    "0"
                ],
                [
                    "906",
                    "1"
                ],
                [
                    "907",
                    "1"
                ],
                [
                    "908",
                    "0"
                ],
                [
                    "909",
                    "0"
                ],
                [
                    "910",
                    "1"
                ],
                [
                    "911",
                    "1"
                ],
                [
                    "912",
                    "0"
                ],
                [
                    "913",
                    "0"
                ],
                [
                    "914",
                    "1"
                ],
                [
                    "915",
                    "0"
                ],
                [
                    "916",
                    "1"
                ],
                [
                    "917",
                    "0"
                ],
                [
                    "918",
                    "1"
                ],
                [
                    "919",
                    "0"
                ],
                [
                    "920",
                    "0"
                ]
            ],
            "model": {
                "dimensions": {
                    "activity": {
                        "dimensionType": "activity",
                        "primaryKey": [
                            "Survived"
                        ],
                        "attributes": {
                            "PassengerId": {
                                "source": "PassengerId",
                                "title": "v bvcbc",
                                "labelfor": "Survived"
                            },
                            "Survived": {
                                "source": "Survived",
                                "title": "cx cx"
                            }
                        }
                    }
                },
                "measures": {}
            }
        }
    ],
    "title": "train",
    "description": "Test desc",
    "govt_level": "Regional",
    "pub_institutional_name": "Datopian",
    "continent": "Africa",
    "periodicity": "Yearly",
    "start_date": "2021-03-06",
    "end_date": "2021-03-13"
}

```

## Tasks

* [x] Ensure that **one non-empty `schema` property exists inside each resource**.
* [x] Ensure that **no `schema` property exists at the top-level** of `datapackage.json` after uploading more than one resource to a new dataset.
* [x] Ensure that a **`sample` property exists for each resource**.
* [x Make sure that the `sample` property is always capped at **maximum 30 rows**.
* [x] Ensure that there is **no `sample` property at the top-level** at any point.

## Analysis

If you look at this file, I've added 3 resources to a newly created repo: https://raw.githubusercontent.com/gift-data/test-crud-dataset-3/045d831c17d1d63250586c9cb04d3febd7f84631/datapackage.json

1. ~~The `sample` property is fine at the top-level (30 rows displayed) but contains too many rows inside the resources. For instance, the first resource in that file is `data/simple_heavy3.csv` and it has 384 rows. We should definitely make sure that the `sample` inside each resource is shorten down to 30 rows maximum.~~ ← We will do the opposite by keeping only a `sample` for each resource (**max. 30 rows**) and discarding the `sample` at the top-level.
2. ~~I wonder why we have a `schema` property inside each resource as well as at the top-level. The schema is shown for the first resource and then is empty for the subsequent resources being added to the dataset (I mean, the `schema` property inside subsequent resources is empty). Shouldn't we discard the `schema` property inside all resources and just keep it at the top-level?~~ ← We will do the opposite by discarding the `schema` at the top-level.

**Comment by sglavoie** [comment]
FIXED: All tasks were done here. The fix will be included once https://github.com/datopian/gift-portal/pull/164 is merged to fix https://github.com/datopian/gift-portal/issues/163.
