### ISSUE TITLE
OS-types should be loaded from a JSON file stored in a GitHub repo every time the table schema page is displayed for the user to see up-to-date types without having to re-deploy the application

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#72]
When I want to edit the OS-types, I want the changes necessary to do so to be simple and the updates to be reflected in the publisher when I access the table schema page so I have a way to easily edit the OS-types without having to modify any code for the portal or publisher applications.

## Acceptance

* [ ] We have a repository (https://github.com/gift-data/os-types) that hosts the types (as a JSON file). \*
  * [ ] Once we get to the table schema page, we fetch the latest type from the JSON file link on GitHub.
* [ ] OS-types can be easily updated by users with a GitHub commit.

\* It looks like having https://github.com/gift-data/os-types (an **empty, private** repo with **no README.md**) breaks the server with a 500 error when loading https://gift-portal-git-master-datopian1.vercel.app/ (I then deleted the repo because of that) so we would need a check to ensure empty repos (private or not) don't cause this kind of issue.

## Tasks

* [ ] Create https://github.com/gift-data/os-types with nothing inside (no README.md or any other file) and make sure it doesn't break the server (500 error) when loading the home page of the portal.
* [ ] When about to display the table schema page, fetch the OS-types from the JSON file link on GitHub (at https://github.com/gift-data/os-types/blob/main/os-types.json).
* [ ] Ensure that when a commit is made to modify https://github.com/gift-data/os-types/blob/main/os-types.json the table schema page loads the updated version.

## Analysis

* GIFT should have an easier way to edit the OS-types. Currently, this is too much work and will lead to issues as we need to make changes in various places and re-deploy the application.
* The proposed solution solves CORS issues as well as where to host the JSON file.

**Comment by risenW** [comment]
@sglavoie 

* Adding os-types repository  to gift-data is not recommended as it will be displayed in the admin page as part of the data packages to edit. So I created it here: https://github.com/datopian/gift-os-types

**Comment by sglavoie** [comment]
Ok, that makes perfect sense. Thanks for the explanation. Just reviewed #73. :slightly_smiling_face:
