### ISSUE TITLE
Tags should not allow empty or duplicate values

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#76]
When I input tags in the metadata page, I want the tool to take care of validation for me so I can be sure that the data published in the portal is coherent.

## Acceptance

* [x] The user cannot enter duplicate values for tags. **Done** https://github.com/datopian/gift-publisher/pull/79
* [x] No empty tags are allowed.
* [x] There is a tooltip when hovering the `Tags` text showing the following description: `Only letters are allowed: tags are single words separated by a comma`

![image](https://user-images.githubusercontent.com/32682903/112517215-ac78b980-8d5d-11eb-9b85-e655e1a89991.png)

## Tasks

* [x] Validate against duplication of values, e.g. the user should not be able to enter `Finance,asdasd,asdasd,dasd` successfully because the tag `asdasd` is there more than once.
* [x] Validate against empty input, e.g. the user should not be able to enter `Finance,asdasd,,ddasd` successfully because that would create an empty tag (same is true for multiple empty tags, e.g. `Finance,,,asdasd,,ddasd,,,,,`).
* [x] Add a tooltip when hovering the `Tags` text showing the following description: `Only letters are allowed: tags are single words separated by a comma`.

## Analysis

Example containing both problems: https://github.com/gift-data/test-new2/blob/9f51d61bf743a8556f63b9e43cf4191984ab75b0/datapackage.json#L12-L17

![image](https://user-images.githubusercontent.com/32682903/112509249-e80f8580-8d55-11eb-952a-e71d82ae678a.png)

Users get confused with how to use the tags, so a simple tooltip should come in handy to clarify what's expected.
