### ISSUE TITLE
The field "Level of government" should be ordered alphabetically and contain the option "Municipal"

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#77]
## Acceptance

* [x] The user can choose "Municipal" in the field "Level of government". **Done** https://github.com/datopian/gift-publisher/pull/78
  * [x] The options are presented in the following order, from top to bottom:
    * Municipal
    * National
    * Provincial
    * Regional
    * State-level

![image](https://user-images.githubusercontent.com/32682903/112517946-869fe480-8d5e-11eb-8f7d-f86f3442911a.png)

## Tasks

* [x] Add the option `Municipal` to the dropdown menu for the field "Level of government".
* [x] Re-order the elements in that dropdown menu alphabetically.
