### ISSUE TITLE
Publisher should handle empty/null values when resources from a dataset are uploaded

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#81]
When I upload a resource to a dataset, I want it to be taken care of by the Publisher/Portal when it contains empty/null values so I can continue using the Publisher/Portal without any issue.

## Acceptance

* [ ] Uploading resources containing empty/null values does not break the Publisher nor the Portal (see **Analysis** for explanations).
* [ ] Resources containing empty values are to be accepted by the Publisher (we only validate the data schema, not the content of the resources).

## Tasks

* [ ] Test against adding resources that contain empty/null values and handle those files adequately.
* [ ] ...

# Analysis

After having uploaded files containing empty values, it seems that this was the direct cause of the server breakdown at https://gift-portal.vercel.app/ :

![image](https://user-images.githubusercontent.com/32682903/114589893-bcddcf00-9c4d-11eb-9545-4ee4a9d0d4b8.png)

The list of problematic files is as follows:
```
costa-rica-presupuesto-egresos-2017/data/egreso2017ene_dic__2017.csv
costa-rica-presupuesto-egresos-2017/data/egreso2017ene_dic.csv
costa-rica-presupuesto-egresos-2018/data/egreso2018ene_dic__2018.csv
costa-rica-presupuesto-egresos-2018/data/egreso2018ene_dic.csv
costa-rica-presupuesto-egresos-2019/data/egreso2019ene_dic__2019.csv
costa-rica-presupuesto-egresos-2019/data/egreso2019ene_dic.csv
costa-rica-presupuesto-egresos-2020/data/egreso2020ene_feb2__2020.csv
costa-rica-presupuesto-egresos-2020/data/egreso2020ene_feb2.csv
croatia-budget-spending/data/croatia-budget-spending.csv
croatia-budget-spending/data/croatia-budget-spending__2018.csv
croatia-budget-spending/data/croatia-budget-spending__2017.csv
croatia-budget-spending/data/croatia-budget-spending__2016.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2010.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2015.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2018.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2019.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2017.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2020.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2008.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2009.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2014.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2013.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2016.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2011.csv
presupuesto-mexico-2008-2019/data/presupuesto_mexico__2012.csv
```

It was posssible to upload pretty much all of them before the error manifested. Croatia and Costa Rica were successfully uploaded but the server got stuck when updating Mexico as can be seen at https://github.com/gift-data/mexico/commits/main (latest changes that were made before the crash).

We have no control whatsoever over the content of the datasets, so the Publisher must support handling null/empty values.
