### ISSUE TITLE
[Dataset merge] A resource concatenating all other resources in a given dataset should be generated/uploaded and added to `datapackage.json`

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#83]
When I update a dataset – either by **re-uploading an existing resource**, by **removing an existing resource** or by **adding a new resource** – I want the tool to merge all the data from that dataset into a single CSV file that I can download separately from the other resources so I have a way to "bulk download" my data.

## Acceptance

* [ ] A CSV file **containing all the resources** (except itself when it exists!) for a given dataset is (re)generated whenever a change is made to the resources of any given dataset (whenever a resource is **re-uploaded**, **removed** or **added**).
  * [ ] It is made available for direct download as a CSV file and appears on the dataset page (e.g. in the **Download** section of a page like https://gift-portal.vercel.app/dataset/south-africa-provincial-estimates-2018-2019).
  * [ ] The `datapackage.json` file is updated accordingly to add or update the necessary metadata about this resource.
* [ ] GitHub Actions is used in the background with a script that does all the work of merging and updating the `datapackage.json` file.

## Tasks

* [ ] Estimate the effort required to deploy the necessary script on GitHub Actions that will be in charge of merging all the data for a dataset whenever it is necessary.
* [ ] TBC.

## Analysis

TBA: in progress.

**Comment by sglavoie** [comment]
@steveoni I tested the `Download All Dataset` feature successfully before, but now it's failing for all datasets. For instance:

* Go to https://gift-portal.vercel.app/dataset/mexico
* Click "Download All Dataset" or go to https://gift-portal.vercel.app/api/dataset/all/MDEwOlJlcG9zaXRvcnkzNjQwMzYzNzc=/org/mexico.csv
* Error displayed on screen: `Error on Retrieve Resource: Trying to add data in unsupported state`.

At first glance, this looks like an issue with encrypting and decrypting the Google key according to [this related question on Stackoverflow](https://stackoverflow.com/questions/51280576/trying-to-add-data-in-unsupported-state-at-cipher-update) (not 100% sure, I don't have the key as an environment variable to test locally) :thinking:.

Could you please have a look at this? :slightly_smiling_face:

**Comment by steveoni** [comment]
@sglavoie to test locally you will need the keys. And for this https://gift-portal.vercel.app/dataset/mexico try it again

I can send you the keys via chat
