### ISSUE TITLE
Porting the validation rules from `os-packager`/`os-types` to validate the "rich types"

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#85]
## Acceptance

* [x] The Publisher tool validates rich types (i.e. the structure and properties of the field object) in the same way it was done in OpenSpending when a user fills out the different fields in the schema editor screen (or more precisely when clicking on `Next` at the bottom to go to the next screen). **Done** See https://github.com/datopian/gift-publisher/pull/86

## Tasks

* [x] List the different validations that need to happen and link to where the original OpenSpending code is located on GitHub (useful for later reference for the client and for ourselves).
* [x] Implement/port the code responsible for the different validations.

## Analysis

*Original analysis in https://github.com/datopian/gift-publisher/issues/82*

At this time, GIFT Publisher validates the schema for resources, but no validation happens for the "rich types". We need to track down where the code that took care of that in the OpenSpending Packager resides. A possible starting point could be here: https://github.com/openspending/os-packager/blob/6b08421f30ebe404d45f331141e76d296a321a6e/app/front/scripts/services/validation.js

This repo should contain the answer as this is the part of the OpenSpending infrastructure that is responsible for packaging a dataset and for letting the user upload it to the platform.

We need to figure out where this validation code is exactly. For instance, the following mappings with the "rich types" should not be possible because the first field is of type year and the second field is an ID, so the chosen value should be rejected by the publisher when clicking "Next".

![2021-05-04_10-50](https://user-images.githubusercontent.com/32682903/117034570-12475200-acc9-11eb-88c3-728b9a47c5ac.png)

**Comment by risenW** [comment]
@sglavoie There are some issues with the final step of porting these rules. 

So far, I've been able to set up the validation to for the rich types, but the issue I'm trying to figure out is how to show/update the state when a selected rich type is invalid.

This problem has to do with the react-select library we initially used, as it is difficult to update the internal state. 

So the major problem I am having here is that if a rich type is invalid I cannot atm, tell the user it's invalid and then clear the field in the UI, instead because it's complicated to update the state, I can atm tell the user the selected type is invalid only. 

I've been doing lots of investigation and research on it, and it seems I might have to remove react-select and go with something simpler, this might make searching when selecting difficult or not available.

**Comment by sglavoie** [comment]
@risenW thank you for your update.

> I can atm tell the user the selected type is invalid only

What do you mean by this? The user will know which field is invalid but the UI won't clear it? If this is the case, isn't it an acceptable situation where the user just has to select a different value for that field?

Also, if the wrong field is not cleared up automatically and the user doesn't change it, can we perform the same validations again when clicking on `Next` at the bottom? The idea would be to make sure the user can't continue to the next step if some validations failed. Would it be possible, when clicking on `Next`, to iterate over all the rich type fields in order (from left to right) and let the user know which field is invalid once one is found to be invalid? And then this could repeat for all faulty selections until no validation issue occurs and the user could go to the next screen.

I'm not sure if that makes sense or would be a possible workaround with what we have so we make sure we don't break other things...

**Comment by risenW** [comment]
@sglavoie This is what I mean:


https://user-images.githubusercontent.com/29900845/118600099-6877c300-b7a8-11eb-9d57-0e5fcb119bf6.mov


You can see that if an invalid type is selected, we can alert the user, but I can't currently clear the selected value. 
Also, when the right rich type is selected, it does not immediately shows in the UI unless I click again. 

All these are caused by the state update, especially as because we are using react-select. I'm going to try another select library and will get back to you if I can complete the issue.

**Comment by risenW** [comment]
FIXED in https://github.com/datopian/gift-publisher/pull/86
