### ISSUE TITLE
The "type" and "rich type" combination should be validated after one of the fields is updated and the Next button should be disabled until no validation issue occurs

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#92]
## Acceptance

* [ ] Users are prevented from going to the next screen if there is a validation issue with any of the fields.

## Tasks

* [ ] Prevent users from clicking `Next` if any validation error occurs (in other words, users cannot go to the next screen if an invalid combination of "type" and "rich type" is selected for any given column in the dataset).
* [ ] Fields should be validated again when updated.
  * [ ] If the "type" field is updated, then a check is done to see if the combination with the "rich type" is valid and either shows an alert and visual feedback (red border) around the input if the selection is not valid, otherwise it displays the combination as valid with no red border around the input (**note:** in the current behavior, the red border around the input for the previously invalid "rich type" field is not removed after updating the "type" field to a valid selection).
  * [ ] If the "rich type" is updated, again the combination of fields "type" and "rich type" for the same column is checked for validation.

## Analysis

**Starting state: all fields are valid**

* Filling all fields correctly allows going to the next screen (OK).

![image](https://user-images.githubusercontent.com/32682903/129730489-5660f556-014d-4264-bd9e-b8c298dd72b8.png)

**State 2: one "type" field is changed to cause the "rich type" field to be invalid**

* Changing a valid field type to an invalid one **should re-trigger validation** in one way or another: now the UI is in an invalid state (without visual feedback around the rich type) but the user can still go to the next screen (not OK).

![image](https://user-images.githubusercontent.com/32682903/129730788-8e923d87-a1d1-4508-87a8-607cd9547247.png)

**State 3: following from state 2, the "rich type" field is updated to get visual feedback and left to an invalid option**

* Users should **not be able to go to the next screen when any validation error occurs**.

![image](https://user-images.githubusercontent.com/32682903/129731552-1d2d58cd-dff9-4741-8711-c0418e33b418.png)

**State 4: validation should be triggered again when updating the "type" field**

Going from this (a "rich type" was selected but the "type" field leads to an invalid combination):
![image](https://user-images.githubusercontent.com/32682903/129731879-9bec1a4b-1ff9-4bd6-a036-9d19220c60e5.png)

To this (now the "type" field is updated, the combination should be valid but is not checked again):
![image](https://user-images.githubusercontent.com/32682903/129731932-fb18a54d-f135-4642-8c4b-002c6024a2b9.png)

* When the "type" field is updated, the validation error from the "rich type" **should be triggered again** and either display an alert if the combination doesn't work or remove the red border around the input if the combination is valid.

---

Showing how users can go to the next screen despite the presence of errors:

![Peek 2021-08-17 07-58](https://user-images.githubusercontent.com/32682903/129729951-4f5ffb88-0469-479e-ad12-a385ad2f6816.gif)

**Comment by steveoni** [comment]
from @sglavoie observation: If I start by choosing a wrong combination, say an integer with the first option in the select dropdown, it generates an error correction, but then if I fill the remaining fields the Next button remains disabled (that's correct), however, if I fix the error for the first field and all fields are valid, it remains disabled...

**Comment by sglavoie** [comment]
FIXED: All tasks were done.
