### ISSUE TITLE
Update the styling of the Rich Type select menu

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#94]
## Acceptance

* [x] The width of the rich type dropdown occupies the full width of the column (see screenshot below for an example of the problem).
* [x] The font color of that component is black (or dark grey) instead of red.

## Tasks

* [x] Update the styles for the rich type select menu in the Publisher.

## Analysis

Steps to reproduce:

* Go to https://gift-portal.vercel.app/dashboard
* Select a dataset where there's a link that says `Create a fiscal data schema` (i.e. no resource uploaded yet).
* Click on the button `Add Resource` and then on `Choose a file to Upload`.
* Upload any random CSV file.
* Click the `Next` button once previewing the dataset.
* Click on any select field showing the placeholder `Select...` to display a dropdown menu with the list of rich types.
* The issue is that the width of the dropdown doesn't fill the width of the column, see screenshot below.

![image](https://user-images.githubusercontent.com/32682903/130972362-2661a437-3cc9-43ba-a1c9-6589eeb175be.png)

Additionally, the fact that it's written in red looks like there's an error.
