### ISSUE TITLE
Make a copy of uploaded file without header

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-publisher#95]
Due to the issue in gift portal https://github.com/datopian/gift-portal/issues/200 , we founding it difficult to have a straight solution approach as stated here https://hackmd.io/@steveoni/BJA9oLPfF. 

We want to be able to create a copy of uploaded  csv files without a header

## Acceptance

- [ ] There should be a copy of the uploaded file without no header stored in google cloud storage
- [ ] There should be a reference to the copied file in the datapackage.json of the respected resource.

## Task

- [ ] Remove the first row of uploaded csv files
- [ ] Create a separate upload instance for the copied files
- [ ] Add the hash of the copied version to datapackage.json

**Comment by sglavoie** [comment]
@steveoni, is there something left to do in this issue? After #96 and https://github.com/datopian/gift-portal/pull/201 were merged, I wasn't able to successfully test the workflow. Here's what happened:

* I removed the resource `budget-vs-actual-national__2015.csv` from https://gift-portal.vercel.app/dataset/south-africa-national-estimates-2015-2019 and re-uploaded it via the dashboard (https://gift-portal.vercel.app/admin/publisher/south-africa-national-estimates-2015-2019).
* Then, I noticed the following.

The resource was successfully uploaded [inside the `copy` directory](https://console.cloud.google.com/storage/browser/_details/gift-datasets/gift-data/copy/984eb7c2e4e5230886f061a76bcb0b4b69889f833eab21866fc08ffe4a7d2d84?project=gift-data) without its header:
![2021-09-20_10-38_1](https://user-images.githubusercontent.com/32682903/134032051-a5334341-44ad-49bf-864c-649f3ca62bee.png)

However, looking inside [the directory of the corresponding dataset ID](https://console.cloud.google.com/storage/browser/gift-datasets/gift-data/MDEwOlJlcG9zaXRvcnkzNzMxNjk5MjU%3D?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) on Google Cloud Storage, no resources were updated:
![2021-09-20_10-38](https://user-images.githubusercontent.com/32682903/134032180-cf3ce368-5850-4955-b912-084516ab5656.png)

Hopefully we can clarify this issue when we'll be meeting.

/cc @nirabpudasaini

**Comment by sglavoie** [comment]
FIXED: Implemented in #96 and successfully tested after re-deploying the portal.
