### ISSUE TITLE
Rich type validation should enable/disable the "Next" button as needed after updating a field

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#97]
## Acceptance

* [ ] Rich types are validated so that the `Next` button is enabled/disabled as needed.
  * [ ] When a wrong selection is made then corrected, the `Next` button is enabled.
  * [ ] When all fields were selected and a wrong selection is made, the `Next` button is disabled.

## Tasks

* [ ] ...

## Analysis

When validating rich type fields, modifying a selection should trigger a new check to enable/disable the `Next` button as needed. The state is updated when a "rich type" is modified but not when the standard "type" is changed.

Standard "type" field is updated → the `Next` button should be disabled.
![Peek 2021-10-06 08-54](https://user-images.githubusercontent.com/32682903/136219063-f82d3c38-6943-4169-9640-48f42c16bf07.gif)

"Rich type" field is updated → the `Next` button should also be disabled.
![Peek 2021-10-06 09-06](https://user-images.githubusercontent.com/32682903/136219258-b563dc35-882d-4089-8f98-c14415416497.gif)

----

/cc @nirabpudasaini

**Comment by SusanBot85** [comment]
@steveoni please confirm that this bug was resolved
